config/routes.rb
Parserapp::Application.routes.draw do
  resources :flights

  resources :airports

  root :to => "main#index"

end

app/models/airport.rb
class Airport < ActiveRecord::Base
  attr_accessible :name, :id
end

app/models/flight.rb
# -*- encoding : utf-8 -*-
class Flight < ActiveRecord::Base
  attr_accessible :arrival_airport, :date, :departure_airport, :econom, :fl

  belongs_to  :from_airport,   :class_name => "Airport", :foreign_key => 'departure_airport'
  belongs_to  :to_airport,   :class_name => "Airport", :foreign_key => 'arrival_airport'

  def to_xml(options = {})
    options.merge!(:only => [:date, :fl, :econom])
    super(options) do |xml|
      xml.airports from_airport.name + '-' + to_airport.name
    end
  end

  # пишем в базу
  def self.writeDB(arr)
    arr.each do |el|
      # пишем аэропорты, если таких еще нет
      Airport.find_or_create_by_name(:name => el[4]).save
      Airport.find_or_create_by_name(:name => el[6]).save

      # проверяем записи по всем полям
      # пишем полеты "туда", если таких еще нет
      from_conditions = {
          :departure_airport => Airport.find_by_name(el[4]).id,
          :arrival_airport => Airport.find_by_name(el[6]).id,
          :date => el[0].split[0],
          :econom => el[8],
          :fl => el[1]
      }
      Flight.where(from_conditions).first || Flight.create(from_conditions)

      # пишем полеты "обратно", если таких еще нет
      to_conditions = {
          :departure_airport => Airport.find_by_name(el[12]).id,
          :arrival_airport => Airport.find_by_name(el[14]).id,
          :date => el[0].split[0],
          :econom => el[16],
          :fl => el[9]
      }
      Flight.where(to_conditions).first || Flight.create(to_conditions)
    end
  end

  # показываем результаты
  def self.showResult(date_start, date_stop)
    return Flight.where(:date => date_start..date_stop)
  end

end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
  # GET /airports
  # GET /airports.json
  def index
    @airports = Airport.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @airports }
    end
  end

  # GET /airports/1
  # GET /airports/1.json
  def show
    @airport = Airport.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @airport }
    end
  end

  # GET /airports/new
  # GET /airports/new.json
  def new
    @airport = Airport.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @airport }
    end
  end

  # GET /airports/1/edit
  def edit
    @airport = Airport.find(params[:id])
  end

  # POST /airports
  # POST /airports.json
  def create
    @airport = Airport.new(params[:airport])

    respond_to do |format|
      if @airport.save
        format.html { redirect_to @airport, notice: 'Airport was successfully created.' }
        format.json { render json: @airport, status: :created, location: @airport }
      else
        format.html { render action: "new" }
        format.json { render json: @airport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /airports/1
  # PUT /airports/1.json
  def update
    @airport = Airport.find(params[:id])

    respond_to do |format|
      if @airport.update_attributes(params[:airport])
        format.html { redirect_to @airport, notice: 'Airport was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @airport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airports/1
  # DELETE /airports/1.json
  def destroy
    @airport = Airport.find(params[:id])
    @airport.destroy

    respond_to do |format|
      format.html { redirect_to airports_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  # GET /flights
  # GET /flights.json
  def index
    @flights = Flight.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @flights }
    end
  end

  # GET /flights/1
  # GET /flights/1.json
  def show
    @flight = Flight.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @flight }
    end
  end

  # GET /flights/new
  # GET /flights/new.json
  def new
    @flight = Flight.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @flight }
    end
  end

  # GET /flights/1/edit
  def edit
    @flight = Flight.find(params[:id])
  end

  # POST /flights
  # POST /flights.json
  def create
    #@flight = Flight.new(params[:flight])
    #@airport = Airport.find(params[:arrival_airport])
    #Airport.find_by_name("IST").id

    @flight = Flight.new(
        :arrival_airport => Airport.find_by_name(params[:flight][:arrival_airport]).id,
        :date => params[:flight][:date],
        :departure_airport => Airport.find_by_name(params[:flight][:departure_airport]).id,
        :econom => params[:flight][:econom],
        :fl => params[:flight][:fl]
    )

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render json: @flight, status: :created, location: @flight }
      else
        format.html { render action: "new" }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /flights/1
  # PUT /flights/1.json
  def update
    @flight = Flight.find(params[:id])

    respond_to do |format|
#      if @flight.update_attributes(params[:flight])
      if @flight.update_attributes(
          :arrival_airport => Airport.find_by_name(params[:flight][:arrival_airport]).id,
          :date => params[:flight][:date],
          :departure_airport => Airport.find_by_name(params[:flight][:departure_airport]).id,
          :econom => params[:flight][:econom],
          :fl => params[:flight][:fl]
      )
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight = Flight.find(params[:id])
    @flight.destroy

    respond_to do |format|
      format.html { redirect_to flights_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/main_controller.rb
# -*- encoding : utf-8 -*-
require 'rest_client'
require 'hpricot'
WebMock.allow_net_connect!

class MainController < ApplicationController
  respond_to :html, :xml, :json

  def index
    @url = 'http://online.nectravel.ru/freight_monitor'

    # нажата кнопка Парсить
    unless params[:commit].nil?

      @arr = main(params[:date_start], params[:date_stop])

      respond_to do |format|
        format.html
        format.json { render "main/index.json.rabl" }
        format.xml { render "main/index.json.rabl" }
      end

    end
  end

  def main(date_start, date_stop)

    date_start = Date.parse(date_start)
    date_stop = Date.parse(date_stop)
    difference_day = (date_stop - date_start).to_i
    date_start_url = date_start.strftime('%Y%m%d')
    url = @url + '?samo_action=FREIGHTS&TOWNFROMINC=2&STATEINC=3&TOWNTOINC=5&CHECKIN=' + date_start_url + '&NIGHTS_FROM=' + difference_day.to_s

    @content = remoteConnect(url)
    @data = getData(@content)
    @arr = parserData(@data)
    Flight.writeDB(@arr)
    return Flight.showResult(date_start.strftime('%d.%m.%Y'), date_stop.strftime('%d.%m.%Y'))
  end

  # получаем контент
  def remoteConnect(url)
    RestClient.proxy = ENV['HTTP_PROXY']
    return RestClient.get(url).body.encode('utf-8', 'windows-1251')
  end

  # берем только нужный контент
  def getData(request)
    request =~ /ehtml\('(.*)'\);/m
    request = $1.gsub(/\n|\\n|\\n\\|\\|,/m, '')
    request = request.gsub(/>\s+</, '><').strip
    return request
  end

  # парсим контент
  def parserData(data)
    arr = []
    Hpricot(data).search("//table[@class='res']/tbody/tr").each { |tr_item|
      r = ''
      tr_item.search("//td").each { |td_item|
        r = r + '|' + td_item.innerHTML.gsub('&nbsp;', '')
      }
      arr.push r.split('|').reject(&:empty?).compact.collect(&:strip)
    }
    return arr
  end

end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/airports/_form.html.haml
= form_for @airport do |f|
  - if @airport.errors.any?
    #error_explanation
      %h2= "#{pluralize(@airport.errors.count, "error")} prohibited this airport from being saved:"
      %ul
        - @airport.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/airports/edit.html.haml
%h1 Editing airport

= render 'form'

= link_to 'Show', @airport
\|
= link_to 'Back', airports_path

app/views/airports/index.html.haml
%h1 Listing airports

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @airports.each do |airport|
    %tr
      %td= airport.name
      %td= link_to 'Show', airport
      %td= link_to 'Edit', edit_airport_path(airport)
      %td= link_to 'Destroy', airport, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Airport', new_airport_path

app/views/airports/new.html.haml
%h1 New airport

= render 'form'

= link_to 'Back', airports_path

app/views/airports/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @airport.name

= link_to 'Edit', edit_airport_path(@airport)
\|
= link_to 'Back', airports_path

app/views/flights/_form.html.haml
= form_for @flight do |f|
  - if @flight.errors.any?
    #error_explanation
      %h2= "#{pluralize(@flight.errors.count, "error")} prohibited this flight from being saved:"
      %ul
        - @flight.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :date
    = f.text_field :date
  .field
    = f.label :flight
    = f.text_field :fl
  .field
    = f.label :departure_airport
    - #= f.number_field :departure_airport
    = f.text_field :departure_airport
  .field
    = f.label :arrival_airport
    -#= f.number_field :arrival_airport
    = f.text_field :arrival_airport
  .field
    = f.label :econom
    = f.text_field :econom
  .actions
    = f.submit 'Save'

app/views/flights/edit.html.haml
%h1 Editing flight

= render 'form'

= link_to 'Show', @flight
\|
= link_to 'Back', flights_path

app/views/flights/index.html.haml
%h1 Listing flights

%table
  %tr
    %th Date
    %th Flight
    %th Departure airport
    %th Arrival airport
    %th Econom
    %th
    %th
    %th

  - @flights.each do |flight|
    %tr
      %td= flight.date
      %td= flight.fl
      - #%td= flight.departure_airport
      - #%td= flight.arrival_airport
      %td= flight.from_airport.name
      %td= flight.to_airport.name
      %td= flight.econom
      %td= link_to 'Show', flight
      %td= link_to 'Edit', edit_flight_path(flight)
      %td= link_to 'Destroy', flight, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Flight', new_flight_path

app/views/flights/new.html.haml
%h1 New flight

= render 'form'

= link_to 'Back', flights_path

app/views/flights/show.html.haml
%p#notice= notice

%p
  %b Date:
  = @flight.date
%p
  %b Flight:
  = @flight.fl
%p
  %b Departure airport:
  = @flight.departure_airport
%p
  %b Arrival airport:
  = @flight.arrival_airport
%p
  %b Econom:
  = @flight.econom

= link_to 'Edit', edit_flight_path(@flight)
\|
= link_to 'Back', flights_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Parserapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/index.html.haml
%div{:style => 'text-align: center;'}
  %h1 Парсер данных туроператора
  %h3 Москва - Турция
  = @url
  = form_tag("/", :method => "post")
  %p
    %input{:type => 'date', :name => 'date_start', :value => Date.today()}
    %input{:type => 'date', :name => 'date_stop', :value => Date.today() + 2.days}

  = radio_button_tag 'format', 'html', true
  = label_tag 'format_html', 'HTML'

  = radio_button_tag 'format', 'xml'
  = label_tag 'format_xml', 'XML'

  = radio_button_tag 'format', 'json'
  = label_tag 'format_json', 'JSON'

  %p
    = submit_tag "Парсить", :disable_with => "Подождите..."


-#%p
-#  = raw @rr

-#- unless @rr.nil?
-#  %p
-#    parse data
-#    %table
-#      - @rr.each do |el|
-#        -#%tr
-#        -#  %td= el
-#        %tr
-#          %td= el[0].split[0] + ' ' + el[1] + ' ' + el[4] + '-' + el[6] + ' ' + el[8]
-#        %tr
-#          %td= el[0].split[0] + ' ' + el[9] + ' ' + el[12] + '-' + el[14] + ' ' + el[16]


- unless @arr.nil?
  %p
    %table{:class => 'tmain'}
      - @arr.each do |el|
        %tr
          %td= el.date
          %td= el.fl
          %td= el.from_airport.name + '-' + el.to_airport.name
          %td= el.econom

app/views/main/search.html.haml
= raw @doc1